title: Bart van der Wal
description: Persoonlijke website en blog
url: "https://bartvanderwal.nl"
baseurl: ""

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Author info
author: Bart van der Wal

# Permalink style
permalink: /:title/

# Exclude from build
exclude:
  - README.md
  - Gemfile.lock
